### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by hioyes** [limxing/LFRecyclerView-Android#1]
07-27 10:55:36.982 4476-4476/me.leefeng.recycleviewdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{me.leefeng.recycleviewdemo/me.leefeng.recycleviewdemo.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class me.leefeng.lfrecycleview.LFRecyclerView
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:168)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                              at android.os.Looper.loop(Looper.java:194)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5398)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:525)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class me.leefeng.lfrecycleview.LFRecyclerView
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                              at me.leefeng.recycleviewdemo.MainActivity.onCreate(MainActivity.java:35)
                                                                              at android.app.Activity.performCreate(Activity.java:5168)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:168) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                              at android.os.Looper.loop(Looper.java:194) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5398) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "me.leefeng.lfrecycleview.LFRecyclerView" on path: DexPathList[[zip file "/data/app/me.leefeng.recycleviewdemo-1.apk"],nativeLibraryDirectories=[/data/app-lib/me.leefeng.recycleviewdemo-1, /vendor/lib, /system/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:552)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at me.leefeng.recycleviewdemo.MainActivity.onCreate(MainActivity.java:35) 
                                                                              at android.app.Activity.performCreate(Activity.java:5168) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:168) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                              at android.os.Looper.loop(Looper.java:194) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5398) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603) 
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by limxing** [comment]
@hioyes 是直接运行的吗？

**Comment by limxing** [comment]
找到原因了，由于使用了一个NewAPI的监听导致6.0以下都报错 抱歉哈
