### ISSUE TITLE
你好，运行在真机上出现问题！

### ISSUE THREAD

**Issue by drluorose** [limxing/LFRecyclerView-Android#2]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.leefeng.recycleviewdemo, PID: 18357
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{me.leefeng.recycleviewdemo/me.leefeng.recycleviewdemo.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class me.leefeng.lfrecycleview.LFRecyclerView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                      at android.app.ActivityThread.access$1200(ActivityThread.java:158)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5564)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class me.leefeng.lfrecycleview.LFRecyclerView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at me.leefeng.recycleviewdemo.MainActivity.onCreate(MainActivity.java:80)
                      at android.app.Activity.performCreate(Activity.java:6013)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                      at android.app.ActivityThread.access$1200(ActivityThread.java:158) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5564) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "me.leefeng.lfrecycleview.LFRecyclerView" on path: DexPathList[[zip file "/data/app/me.leefeng.recycleviewdemo-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:590)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:825) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:523) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:425) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:368) 
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at me.leefeng.recycleviewdemo.MainActivity.onCreate(MainActivity.java:80) 
                      at android.app.Activity.performCreate(Activity.java:6013) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                      at android.app.ActivityThread.access$1200(ActivityThread.java:158) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5564) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                    Suppressed: java.lang.ClassNotFoundException: Didn't find class "me.leefeng.lfrecycleview.LFRecyclerView" on path: DexPathList[[dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-support-annotations-24.1.1_8a03d8c96280e3fb84b1249ccb928b3d433e85b7-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/instant-run/dex/slice-picasso-2.5.2_4a878b698ef283cc6593e252f294c70b265624d5-classes.dex", dex file "/data/data/me.leefeng.recycleviewdemo/files/insta
I/Process: Sending signal. PID: 18357 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by limxing** [comment]
找到原因了，由于使用了一个NewAPI的监听导致6.0以下都报错

**Comment by drluorose** [comment]
谢谢！

**Comment by drluorose** [comment]
华为机器还是崩溃，android版本是5.0.2

**Comment by drluorose** [comment]
View.OnScrollChangeListener 在api 23一下不能用，有什么好的替代方案吗？

**Comment by limxing** [comment]
@drluorose 直接运行的话，我手头边：小米4.4三星5.0华为6.0都是可运行的，gmail给您邮件了
