### ISSUE TITLE
老版本 viewpager兼容有问题，，LFRecyclerView.setAdapter 在切换fragment时observer 报空异常

### ISSUE THREAD

**Issue by wpsmgkn** [limxing/LFRecyclerView-Android#7]
java.lang.IllegalArgumentException: The observer is null.
                                                                 at android.database.Observable.registerObserver(Observable.java:45)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.registerAdapterDataObserver(RecyclerView.java:6492)
                                                                 at me.leefeng.lfrecyclerview.LFRecyclerView.setAdapter(LFRecyclerView.java:100)

**Comment by limxing** [comment]
我添加了一个判断，看看能满足你的需求不 

@Override
    public void setAdapter(Adapter adapter) {
        this.adapter = adapter;
        if(observer==null)
            observer = new LFAdapterDataObserver();
        adapter.registerAdapterDataObserver(observer);
